### ISSUE TITLE
Joomla name usage

### ISSUE THREAD

**Issue by brianteeman** [joomla/user-interface-text#43]
We currently have a mix of Joomla! and Joomla in the UI and we should have a set of rules to follow that both follow the TM and enhance readability. And we are not using the ® symbol

I have been trying to get an answer from the TM team via @duke3d for quite a while but without response. @MAT978 did provide this documentation https://github.com/joomla/user-interface-text/blob/master/joomla_name_usage.md but I am not really sure how we can apply that to the UI

### Tooltip
COM_BANNERS_FIELD_ALIAS_DESC="The alias is for internal use only. Leave this blank and Joomla will fill in a default value from the title. It has to be unique for each banner in the same category."

### Label
COM_CONFIG_FIELD_METAVERSION_LABEL="Show Joomla! Version"

### Heading
COM_JOOMLAUPDATE_VIEW_COMPLETE_HEADING="Joomla! Version Update Status"

### Description
COM_JOOMLAUPDATE_XML_DESCRIPTION="Updates Joomla! to the latest version with one click."

### Progress Bar
COM_JOOMLAUPDATE_VIEW_UPDATE_INPROGRESS="Updating your Joomla! files. Please wait ..."

**Comment by MAT978** [comment]
Whereas the only real difficulty is the use or not of the "!" for Joomla.

Each of us can have an opinion or preference (I have one: simplicity is always the  best) but I guess we will ALL agree to find a solution to the standardization, consistency and simplicity of implementation.

Personally, I always use Joomla! with the "!" EXCEPT when there is a conflict with punctuation like for example in my previous sentence: "blablabla not of the "!" for Joomla."
there is a final dot (this can be a comma, a question mark etc.), so I do not use it.
Elsewhere I always use Joomla! not because I like this way but because at this point, it IS Joomla! with the "!".

Note that this is not a "legal" analysis in connection with the trademark usage but just a consistency in my use and never forget that english is not my native language then I may be wrong.

**Comment by brianteeman** [comment]
Personally i only use the ! when it is not being used in a general way.

I dont really care which I just want consistent usage and a guideline for
others to follow.

  I am happy to correct the core language files to follow that. I am just
reluctant to do that and have then the TM team come back and say it is
wrong.

To be honest the TM team should have addressed this a long time ago

**Comment by MAT978** [comment]
<quote>when it is not being used in a general way.</quote>

I understand and I think you're right BUT, IMHO, the problem with this "vision" is the subjective aspect of the case by case...

if you are alone, there will be no problems but what "in a general way" really is for x, y, z?

anyway, these are really details...
(Hummm, I like details ;) )

**Comment by brianteeman** [comment]
In my head the examples above are correct.

When referring to the organisation always use the ! and when referring to the software, as in Joomla will do x, then dont use the !

**Comment by jessicadunbar** [comment]
Hey @brianteeman and @MAT978 does this help?  https://github.com/joomla/joomla-cms/pull/4455#issuecomment-58395711

**Comment by brianteeman** [comment]
Thanks for the link but not really as I see this use case as different.
@duke3d had said he would let me know about this use case but I havent
heard from him

**Comment by brianteeman** [comment]
As you can see I am reluctant to do anything without confirmation from the
TM team regarding this use case

On 28 January 2015 at 17:09, Brian Teeman <brian@teeman.net> wrote:

> Thanks for the link but not really as I see this use case as different.
> @duke3d had said he would let me know about this use case but I havent
> heard from him
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by Hils** [comment]
>And we are not using the ® symbol

@brianteeman why is that please?

**Comment by brianteeman** [comment]
I have no idea. There is no existing documentation for anything regarding
the core language. That is what we are trying to correct here and then to
apply that to the core.

On 28 January 2015 at 17:18, Hils <notifications@github.com> wrote:

> And we are not using the ® symbol
>
> @brianteeman <https://github.com/brianteeman> why is that please?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/user-interface-text/issues/43#issuecomment-71875352>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by Hutchy68** [comment]
We used to have it. Even discussed it here. https://groups.google.com/forum/m/#!topic/joomla-dev-general/tRiJvzeO-XI

**Comment by MAT978** [comment]
You DO already (using the on the ®) on the admin log + cpanel

why should you claim the property elsewhere?
Using it in technical core strings is just a nonsense as you can't even specify the first use... 
then what should you do when using in the same sentence Joomla! (registered) then Joomla (not registered) :D

**Comment by Hils** [comment]
Joomla! is registered. Think of things as a whole not separate parts. Joomla! is registered but, eg. Joomla! Extension Directory is not registered but we can claim it as a Trade Mark. The Joomla exclamation mark only needs to be used once on a page unless it is part of a Trade Mark, for the first time. This has always been the case but many of us have never understood it.

example:
<h5>The Joomla!® Project </h5>
<p>Joomla has a specific way of dealing with extensions and they are all available for download via the Joomla! Extensions Directory™.</p>

Of course  ® should be superscript but that example is how I understand it from Duke.

**Comment by brianteeman** [comment]
This is exactly why we need specific instructions from the TM team

On 28 January 2015 at 18:56, Hils <notifications@github.com> wrote:

> Joomla! is registered. Think of things as a whole not separate parts.
> Joomla! is registered but, eg. Joomla! Extension Directory is not
> registered but we can claim it as a Trade Mark. The Joomla exclamation mark
> only needs to be used once on a page unless it is part of a Trade Mark, for
> the first time. This has always been the case but many of us have never
> understood it.
>
> example:
> The Joomla!® Project
>
> Joomla has a specific way of dealing with extensions and they are all
> available for download via the Joomla! Extensions Directory™.
>
> Of course ® should be superscript but that example is how I understand it
> from Duke.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/user-interface-text/issues/43#issuecomment-71893028>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by MAT978** [comment]
Sorry... 
I do not understand where is the confusion?

**Comment by MAT978** [comment]
@Hils 
sorry to bother you but to prevent any misunderstanding ;) could you explain more specifically what you mean here: "The Joomla exclamation mark only needs to be used once..."?
are you talking about the "!" or the TM sign?

**Comment by Hils** [comment]
In en-GB grammar we call it an exclamation mark - elsewhere in the world eg North American, it is called a bang. So I am specifically talking about the ! .

**Comment by MAT978** [comment]
thanks for this explanation but then, if you are talking about the "exclamation mark", then you are confusing the procedure to apply for the  for the ™ and/or the ®.

the "use it once on the first use" only concern those 2 signs, NOT the (!)

Please could you check again:
https://github.com/joomla/user-interface-text/blob/master/joomla_name_usage.md
then tell me if this point is confusing?
Thanks

**Comment by MAT978** [comment]
example, when you use 20 times on a page "the Joomla! Extensions Directoy", it is necessary to mark the TM sign for the first use "the Joomla! Extensions Directory™" and you will have to use as many "!" for Joomla! as needed on the same page...

**Comment by Hils** [comment]
It is probably me confusing you. The Joomla registered mark is Joomla!®

But after that has been used once, we can revert to using just Joomla. 

But if we write about JED,  it should be Joomla! Extensions Directory™ as should The Joomla! Community Magazine™ .

**Comment by Hils** [comment]
If we used the Joomla! Extensions Directory™ 20 times, surely we would say Joomla! Extensions Directory™ (JED) and then be free to name it JED ? Keep the tm separate from the reg! "Joomla! Extensions Directory™" that is one entity.

**Comment by mbabker** [comment]
But how do we know within the UI whether Joomla! Extensions Directory™ has been used anywhere or whether the acronym is defined?  Likewise, if we intend to display the registered or trade marks with our intellectual property, how do we know where that should be?

Adding to the complexity is what modules or strings may or may not be displayed on the page.  For example, Hathor still has the `JGLOBAL_ISFREESOFTWARE="Joomla!® is free software released under the GNU General Public License."` string displayed in its footer, Isis does not.  So it almost feels like to me at the moment the options are either every mark has its respective indicator displayed with it or no marks display it.

**Comment by brianteeman** [comment]
> But after that has been used once, we can revert to using just Joomla.

No that is not correct. At least from my understanding you always have to
use the !

I haven't seen anything written anywhere about not having to use the !

(Maybe my memory is wrong on this?)

On 28 January 2015 at 20:44, Hils <notifications@github.com> wrote:

> If we used the Joomla! Extensions Directory™ 20 times, surely we would say
> Joomla! Extensions Directory™ (JED) and then be free to name it JED ? Keep
> the tm separate from the reg! "Joomla! Extensions Directory™" that is one
> entity.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/user-interface-text/issues/43#issuecomment-71912068>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
In the other thread @jessicadunbar wrote

> The common exception for not consistently using the bang is in body text when making a vague reference to Joomla, such as talking about "Joomla compatible plugins" and "the Joomla community."

This is what I am hoping the TM team will say as it makes the most sense but we will just have to wait for them. It is not for us to make a decision. I have reached out in as many ways as I can to the TM team lead and OSM liaison on this but with no luck so I guess this will miss the 3.4 release

**Comment by Hutchy68** [comment]
Joomla! first use on a page and Joomla without ! on subsequent usage. This was on the OSM website. Since the update I can't find it. There are links to all the old documentation on OSM but that information is not there. 

I think you are not required to use the ® or ™ by law. It is just recommended for your protection. I have seen similar wording to use the registered mark with the first occurrence or it could be prominent usage on a page.

**Comment by brianteeman** [comment]
Until Duke reappears I suggest we stop wasting our time on this one

**Comment by MAT978** [comment]
1- Brian is right!
2- Tom is right on his second §

**Comment by Hils** [comment]
Yup, the boys must be right. This has been discussed since we began the magazine!

**Comment by Hils** [comment]
What bit, from Duke, of this do we not understand?


 Joomla! is our registered mark. As such, with the first predominant use of the mark on a Joomla-related page, we request that the circle-R indicia be included along with a footer that explains that the mark is registered and owned by OSM. We do not consider including the name Joomla! as a menu item, where the name and logo are at the same size as other menu links, to be a predominant use so there is no need to add the circle-R to "Joomla!" when it appears as a menu item linking to the home page. Only add it when Joomla! is appearing as a site logo or in a major heading or title such as in an h1, h2 or h3 tag.

In short, we only need to give notice to the world of our claim to ownership once on a page.

This applies to "our" pages. I consider sample data to be a gray area that serves as a starting point for end user pages. In sample data, we should be consistent in following the style guide with regard to when to include the exclamation point, but there is no great need to include the circle-R or TM indicia. They learned that we owned the trademark when they downloaded the software, so no need to provide redundant notice of trademark ownership.

One other topic - when to use TM and when to use circle-R. Circle-R only applies to the use of Joomla! (or Joomla! plus the logo design) standing alone, outside the context of a more specific product or service name. If Joomla! is part of a longer product or service name such as Joomla! 3.3 or Joomla! Framework or Joomla! Developer Network, then the entire phrase is serving as the proper name for that specific product or service. Therefore the phrase IS is trademark and should have the TM indicia included with the first dominant use of the mark on a page. These phrases are NOT registered even though they ARE trademarks and service marks and so a superscript circle-R should NOT be used and instead a superscript TM should be used.

**Comment by brianteeman** [comment]
He said it was not relevant in our use case and he would write the
guidelines

**Comment by MAT978** [comment]
"He said it was not relevant in our use case"
+:100:

**Comment by Hils** [comment]
oh ok where did Duke say that? Is everything I have said incorrect?

**Comment by brianteeman** [comment]
In a private conversation or I would have pasted it here

On 28 January 2015 at 22:43, Hils <notifications@github.com> wrote:

> oh ok where did Duke say that? Is everything I have said incorrect?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/user-interface-text/issues/43#issuecomment-71932614>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by Hils** [comment]
No comment

**Comment by brianteeman** [comment]
Sorry but the request for Duke to check was made on skype and his reply
that it needed more that the would provide was also on skype and I do not
publish the content of private conversations. That would be wrong.

As I stated before I am not wasting any more time on this issue - and
neither should anyone else - until the TM team respond. Only they are the
ones tasked with the authority by the project to make a decision. We can
only implement the decision

On 28 January 2015 at 23:03, Hils <notifications@github.com> wrote:

> No comment
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/user-interface-text/issues/43#issuecomment-71935646>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by rgmears** [comment]
@brianteeman

The linked to page below presents the Joomla! name the way you suggest.
[Built with Joomla!](http://studiofive.ca/built-with-joomla.html)

I think it would be better &mdash; regardless of what Duke says about the &reg; usage &mdash; to stop using the ! (exclamation mark / bang). Which means changing Joomla!'s official name from Joomla! to Joomla.

**Comment by Duke3D** [comment]
Apologies to all for my extended incapacity.  
I have edited the page that was kindly put together by MAT.  

Let me recap a couple items.

@rgmears Robert - dropping the bang is certainly an option, but that would be a board level decision.  It is above my pay grade and beyond our scope here.  It is like legally getting your name changed.  The primary objection is cost as it would require all of our trademarks to have to be applied for again, around the world.  By analogy, moving the property line for your house by .001% is nevertheless a change that requires the full treatment - a plat and a deed needs to be recorded.

--------

The role of a trademark indicia is to give notice.  Concerning the backend of a Joomla website, to get to where a user would either see language strings, they have already encountered the Joomla branding and trademark notices, therefore additional notice is not necessary.  The entry point of the backend (either the login module or the logo on the dashboard/landing page) should be the point where we declare our trademark ownership.  Once they have passed by that signpost, it doesn't matter where they travel or what they view in the backend, they have received notice.  So, on that point, I see no reason for circle-R to appear anywhere else in the backend, since it has already been placed on the login module.  (AFAIK/remember - This is the use case that @brianteeman and I discussed sidebar.)

Other Joomla trademarks -
There is one feature I can think of in the Joomla backend that involves a more specific Joomla-related trademark.  (There may be more - please point them out.)  That is the "Install from Web" feature.  In my humble opinion this feature should be more accurately renamed to "Install from JED" to distinguish it from a true install from any web URL feature.  Regardless, any place the descriptive text makes reference to the Joomla! Extensions Directory, it should have the bang, and the first use should also have the TM indicia.

@Hils had an excellent example.  The first reference can be to the Joomla! Extensions Directory™ (JED) and from then on you could refer to simply the JED™ which has also gained trademark significance.  

Turning to the bang.  
Unlike with trademark indicia, the rule here is not about first use, it is about whether a use is a branding use, which is a very vague and confusing concept.  The short answer is that any time we are using Joomla! in a logo, a major headline, or an artistic illustration such that it suggests the source of the goods or services, this is considered a branding use and therefore it should be a complete expression of our proper name, including the exclamation point.  Whenever we are using Joomla as part of a description, including any time it is in body text, then the bang should be omitted to improve readability.  

In general, use in body text is a descriptive and not a branding use.  The Joomla name in text can become a branding use if you start talking about specific products or services as if they are tangible things, like Joomla! 3.4, or the Joomla! Resources Directory.  Because these are trademarks and also they are unregistered trademarks, extra care is needed to use them consistently to retain their trademark status.  The registration and broader recognition of the Joomla! wordmark is why we have more flexibility with the Joomla name being without the bang in a descriptive context than we do with these specific Joomla-related products and services.

A vague reference to the Joomla CMS, your Joomla website or the Joomla community does not need and should not have the exclamation point.  In the specific case of error messages, language strings, and comments in code, there is no need to include an exclamation point as these are not branding uses and the unnecessary punctuation will add confusion.  The branding use in this context is the logo appearing at the top of the administrator pages and possibly certain page headings (built-in help) or quick icons (Your Joomla! is up to date.)  If the page is properly branded, any content that might appear within the page does not need to meet branding requirements.  

I submitted a PR with the revised guidelines, but kept it short.  It may need more specific statements added for these particular areas.  Suggestions in this regard are appreciated.  

The one rule that we will frequently violate in the context of inside the software is not using Joomla as a noun.  That is because we frequently use Joomla as a shorthand nickname for the Joomla! CMS, especially when we are inside of that Joomla environment.  As a practical matter, the guideline about using Joomla as a noun can be ignored inside the software environment.  This really applies to and is important in connection with our public-facing marketing materials and published marketing oriented web content on J.org, not our code, documentation, tutorials and similar user-facing content.  Users can be presumed to have repeatedly seen and thus already know both our full proper name and our claim of trademark as they have passed many prominent signposts along the pathway leading to our help pages and administrative screens.  

Absent a reference to a more specific Joomla-related product or service, using Joomla without an exclamation point is preferred within descriptive text and in the code, including language strings.

**Comment by brianteeman** [comment]
Can you give specific examples see #46

**Comment by brianteeman** [comment]
Also reading your comments here a large percentage of what you have written
in the doc does not apply here as we are only talking about usage within
the language strings of the cms. Please can you update the doc so that it
only concerns this usage which is all that this style guide is for. Thanks

**Comment by brianteeman** [comment]
Sorry the list of specific examples is #47

**Comment by rgmears** [comment]
@Duke3D
> dropping the bang is ... is like legally getting your name changed. The primary objection is cost as it would require all of our trademarks to have to be applied for again, around the world. 

I am aware of that.

**Comment by Duke3D** [comment]
Brian wrote -
"Also reading your comments here a large percentage of what you have written in the doc does not apply here as we are only talking about usage within the language strings of the cms. Please can you update the doc so that it only concerns this usage which is all that this style guide is for. Thanks"

Sorry, I am still unclear about where this doc will be posted and who would see it.  There is some advantage to general education of the community as evidenced by the discussion leading up to this.  I already tightened some of the specifics in a PR I submitted before seeing this note.  If you want this laser-focused to just code strings, we can do that.  Just going through this exercise and the examples has helped me become much clearer about what is and is not needed in the backend and in user-facing documentation.  A major difference from the rules we are applying to marketing docs and the community.  Let me know if you want another pass at simplifying.

**Comment by Duke3D** [comment]
Also, don't hesitate to redline whatever you think is irrelevant / superfluous.

**Comment by brianteeman** [comment]
The only purpose of this style guide is outlined here
https://github.com/joomla/user-interface-text/blob/master/README.md

So yes it should be laser focussed.

**Comment by brianteeman** [comment]
This has now been merged - thanks
