### ISSUE TITLE
Joomla name usage examples

### ISSUE THREAD

**Issue by brianteeman** [joomla/user-interface-text#47]
Examples of current usage

### Tooltip and Descriptions

* COM_BANNERS_FIELD_ALIAS_DESC="The alias is for internal use only. Leave this blank and Joomla will fill in a default value from the title. It has to be unique for each banner in the same category."  
* COM_CONFIG_FIELD_LOG_PATH_DESC="For logging of Joomla. Please specify a folder."  
* COM_CONFIG_FIELD_PROXY_ENABLE_DESC="Enable Joomla to use a proxy which is needed in some server environments in order to fetch URLs like in the Joomla! Update component."  
* COM_CONFIG_FIELD_DEBUG_LANG_DESC="Select whether the debugging indicators (<bold>**...**</bold>) or (<bold>??...??</bold>) for the Joomla! Language files will be displayed. Debug Language will work without Debug System being activated, but you will not get the additional detailed references that will help you correct any errors.  
* COM_CONFIG_FIELD_DEBUG_SYSTEM_DESC="If enabled, diagnostic information, language translation and SQL errors (if present) will be displayed. The information will be displayed at the foot of every page you view within the Joomla Backend and Frontend. It is not advisable to leave the debug mode activated when running a live website."
* COM_JOOMLAUPDATE_XML_DESCRIPTION="Updates Joomla! to the latest version with one click."
* COM_CPANEL_MSG_EACCELERATOR_TITLE="eAccelerator is not compatible with Joomla!"
* COM_CONFIG_FIELD_LOG_PATH_DESC="For logging of Joomla. Please specify a folder."

### Label

COM_CONFIG_FIELD_METAVERSION_LABEL="Show Joomla! Version"

### Heading

COM_JOOMLAUPDATE_VIEW_COMPLETE_HEADING="Joomla! Version Update Status"

### Progress Bar

COM_JOOMLAUPDATE_VIEW_UPDATE_INPROGRESS="Updating your Joomla! files. Please wait ..."

**Comment by brianteeman** [comment]
@Duke3D I have read your doc - thanks - can you please take the examples of CURRENT strings and advise on the correct usage in each example. Then we can apply them - specifically the comment about using joomla as a regular noun has considerable impact

**Comment by Duke3D** [comment]
Rule of thumb - Whenever you can substitute "your Joomla CMS" in place of "Joomla" and still make sense, then it's descriptive and no bang needed.  
If it breaks apart the proper name of a branded or promoted product or feature, then the bang is probably appropriate.

Tooltip and Descriptions

COM_BANNERS_FIELD_ALIAS_DESC="The alias is for internal use only. Leave this blank and Joomla will fill in a default value from the title. It has to be unique for each banner in the same category." *    

No change - a proper descriptive reference.

COM_CONFIG_FIELD_LOG_PATH_DESC="For logging of Joomla. Please specify a folder."

No change  (except incomplete sentence / no reference what is being logged - messages? status? errors?)

COM_CONFIG_FIELD_PROXY_ENABLE_DESC="Enable Joomla to use a proxy which is needed in some server environments in order to fetch URLs like in the Joomla! Update component."

No change - the reference to Joomla! Update component is as a proper name.

    COM_CONFIG_FIELD_DEBUG_LANG_DESC="Select whether the debugging indicators (...) or (??...??) for the Joomla! Language files will be displayed. Debug Language will work without Debug System being activated, but you will not get the additional detailed references that will help you correct any errors.

Could be either way, but I think the intention is descriptive despite the uppercase L on Language suggesting a proper name.
My sense - go with ... Joomla language files ...  no bang / lower case L

    COM_CONFIG_FIELD_DEBUG_SYSTEM_DESC="If enabled, diagnostic information, language translation and SQL errors (if present) will be displayed. The information will be displayed at the foot of every page you view within the Joomla Backend and Frontend. It is not advisable to leave the debug mode activated when running a live website."

No change

COM_JOOMLAUPDATE_XML_DESCRIPTION="Updates Joomla! to the latest version with one click."

Mid-sentence in a description - no bang.

COM_CPANEL_MSG_EACCELERATOR_TITLE="eAccelerator is not compatible with Joomla!"

The reason to include the bang is because the sentence is an exclamation even if Joomla was not the object.  e.g.  "eAccelerator is not compatible with your software!"  If not intended as an exclamatory, then no-bang.

COM_CONFIG_FIELD_METAVERSION_LABEL="Show Joomla! Version"

Despite capitalized initials signifying a proper name I think the use is intended to be descriptive. 
Use either "Show Joomla! Version" or "Show Joomla version" and I think the intent is the later.

COM_JOOMLAUPDATE_VIEW_COMPLETE_HEADING="Joomla! Version Update Status"
Progress Bar

Capitalized initials signify a proper name so bang is appropriate.

COM_JOOMLAUPDATE_VIEW_UPDATE_INPROGRESS="Updating your Joomla! files. Please wait ..."

No bang - descriptive

Brian Teeman
Collaborator
brianteeman commented 2 hours ago

@Duke3D I have read your doc - thanks - can you please take the examples of CURRENT strings and advise on the correct usage in each example. Then we can apply them - specifically the comment about using joomla as a regular noun has considerable impact
Brian Teeman brianteeman referenced this issue an hour ago
Open
Joomla name usage #43
Duke3D

    Write
    Preview

Markdown supported
Edit in fullscreen

Attach images by dragging & dropping or selecting them.

**Comment by brianteeman** [comment]
@duke3d as documented elsewhere in the styleguide (
https://github.com/joomla/user-interface-text/blob/master/capitalisation.md)
there are "style" rules in use for capitalisation that I "think" may have
relevance to some of your comments above

**Comment by Duke3D** [comment]
Taking a look - thanks

**Comment by Duke3D** [comment]
Another pass using the simpler rules.

Tooltip and Descriptions

COM_BANNERS_FIELD_ALIAS_DESC="The alias is for internal use only. Leave this blank and Joomla will fill in a default value from the title. It has to be unique for each banner in the same category." *    

No change.

COM_CONFIG_FIELD_LOG_PATH_DESC="For logging of Joomla. Please specify a folder."

No change.

COM_CONFIG_FIELD_PROXY_ENABLE_DESC="Enable Joomla to use a proxy which is needed in some server environments in order to fetch URLs like in the Joomla! Update component."

Joomla! Update component ==> Joomla Update component 

    COM_CONFIG_FIELD_DEBUG_LANG_DESC="Select whether the debugging indicators (...) or (??...??) for the Joomla! Language files will be displayed. Debug Language will work without Debug System being activated, but you will not get the additional detailed references that will help you correct any errors.

Joomla! Language files ==> Joomla language files

    COM_CONFIG_FIELD_DEBUG_SYSTEM_DESC="If enabled, diagnostic information, language translation and SQL errors (if present) will be displayed. The information will be displayed at the foot of every page you view within the Joomla Backend and Frontend. It is not advisable to leave the debug mode activated when running a live website."

No change

COM_JOOMLAUPDATE_XML_DESCRIPTION="Updates Joomla! to the latest version with one click."

Updates Joomla! to ==> Updates Joomla to

COM_CPANEL_MSG_EACCELERATOR_TITLE="eAccelerator is not compatible with Joomla!"

The reason to include the bang is because the sentence is an exclamation even if Joomla was not the object.  e.g.  "eAccelerator is not compatible with your software!"  If not intended as an exclamatory, then no-bang.

COM_CONFIG_FIELD_METAVERSION_LABEL="Show Joomla! Version"

Show Joomla! Version ==> Show Joomla Version

COM_JOOMLAUPDATE_VIEW_COMPLETE_HEADING="Joomla! Version Update Status"
Progress Bar

Joomla! Version Update Status Progress Bar ==> Joomla Version Update Status Progress Bar

COM_JOOMLAUPDATE_VIEW_UPDATE_INPROGRESS="Updating your Joomla! files. Please wait ..."

your Joomla! files ==> your Joomla files

**Comment by brianteeman** [comment]
I have added the following to the main document as it is easy to understand
Rule of thumb - Whenever you can substitute "your Joomla CMS" in place of "Joomla" and still make sense, then it's descriptive and no bang needed.
